### ISSUE TITLE
waiver claims not coming through

### ISSUE THREAD

**Issue by nickbalto** [StoneMasons4106/sleeper-ffl-discordbot#2]
add/drops - working
drops - not working
waivers claims/auctions - not working

**Comment by StoneMasons4106** [comment]
> add/drops - working
> drops - not working
> waivers claims/auctions - not working

You'll have to be a bit more specific... first off what's your Sleeper league ID so I can test this in the test server? Are you referring to the trending-players command and waiver-order command? The waiver-order command is a Patron only command just so you're aware.

**Comment by nickbalto** [comment]
Apologies. 

The transactions from when waivers process do not come through. 

[https://i.imgur.com/3dCNCAI.png](https://i.imgur.com/3dCNCAI.png)

**Comment by StoneMasons4106** [comment]
> Apologies. 
> 
> The transactions from when waivers process do not come through. 
> 
> [https://i.imgur.com/3dCNCAI.png](https://i.imgur.com/3dCNCAI.png)

I see, ill look into this.

**Comment by nickbalto** [comment]
Thanks. 

league ID is 664348755822186496

**Comment by StoneMasons4106** [comment]
> Thanks.
> 
> league ID is 664348755822186496

I just reworked the transaction command logic so that it looks for both an add and a drop every time the transaction is a free agent move or waiver move. I'm assuming you're in a server that has access to patron commands?

**Comment by StoneMasons4106** [comment]
Closing as transactions command has been fixed when called.
