### ISSUE TITLE
Invalid Permissions Provided

### ISSUE THREAD

**Issue by BravesVolsUU** [StoneMasons4106/sleeper-ffl-discordbot#3]
Wanted to invite the bot to my Discord I made for my dynasty league this week. Unfortunately, when I click on the invite link on the readme, it says "invalid permissions provided" on the popup.

**Comment by StoneMasons4106** [comment]
> Wanted to invite the bot to my Discord I made for my dynasty league this week. Unfortunately, when I click on the invite link on the readme, it says "invalid permissions provided" on the popup.

Do you have Adminstrator permissions on the server? Sounds like a permissions error on the Discord server side rather than the bot

**Comment by BravesVolsUU** [comment]
Yes, I have Admin permissions turned on. I'm trying to figure out what else it could be on my side...

**Comment by StoneMasons4106** [comment]
> Yes, I have Admin permissions turned on. I'm trying to figure out what else it could be on my side...

Found it. Looks like since Discord changed their integration the scopes changed. You should be able to invite it now from top.gg.
