### ISSUE TITLE
Only you can see this 

### ISSUE THREAD

**Issue by Ange1z** [StoneMasons4106/sleeper-ffl-discordbot#5]
How do I get the bot to stop doing "only you can see this message"? Id like it to be when you do a command anyone can see...

**Comment by StoneMasons4106** [comment]
Yeah that's a hardcoded feature. I didn't want people to be pinged every time someone called a command as I know I find that annoying. And if you want someone to see the result of what you called, it's usually for trash talking purposes (scores, standings, etc....). The only commands that aren't ephemeral would be the kick, ban, and unban commands.
