### ISSUE TITLE
Making messages public for everyone

### ISSUE THREAD

**Issue by Shredmonds** [StoneMasons4106/sleeper-ffl-discordbot#7]
Hi! So far I really like the bot.  However, whenever I run a command, it says the message is only visible to me.  Is it possible to have the message be visible to everyone in the server?  Also, is it possible to schedule messages from sleeper-ffl to a certain text channel?

Thanks!

**Comment by StoneMasons4106** [comment]
To answer both questions:

That is an intended feature right now so not everyone is constantly pinged every time someone uses the bot. I may add it as optional later but we'll see.

As far as scheduling messages go, use the syntax /set-channel <channel-id>. The channel ID is obtainable through right clicking the channel and hitting copy ID. Make sure you have Developer settings enabled so you can get the ID.
